// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoreApi.Data;

#nullable disable

namespace StoreApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206064018_Add-Shopping-Cart-And-Items")]
    partial class AddShoppingCartAndItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StoreApi.Model.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("StoreApi.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Категория 5",
                            Description = "Шагов плановых настолько степени.",
                            Image = "https://picsum.photos/640/480/?image=150",
                            Name = "Потрясающий Пластиковый Стол",
                            Price = 843.71000000000004,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Категория 2",
                            Description = "Подготовке повседневной форм оценить настолько дальнейшее новых не базы.",
                            Image = "https://picsum.photos/640/480/?image=175",
                            Name = "Интеллектуальный Пластиковый Портмоне",
                            Price = 991.09000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Категория 3",
                            Description = "Направлений сфера кадровой повседневной способствует важную особенности рост намеченных модернизации.",
                            Image = "https://picsum.photos/640/480/?image=866",
                            Name = "Потрясающий Меховой Ботинок",
                            Price = 632.70000000000005,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Категория 5",
                            Description = "Эксперимент создаёт сомнений новая гражданского обществом.",
                            Image = "https://picsum.photos/640/480/?image=1020",
                            Name = "Грубый Пластиковый Свитер",
                            Price = 996.25,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Категория 4",
                            Description = "Прогрессивного рамки представляет поставленных соответствующей последовательного.",
                            Image = "https://picsum.photos/640/480/?image=288",
                            Name = "Практичный Пластиковый Ножницы",
                            Price = 861.32000000000005,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Категория 1",
                            Description = "Правительством национальный укрепления задания повышению таким высшего.",
                            Image = "https://picsum.photos/640/480/?image=648",
                            Name = "Лоснящийся Хлопковый Клатч",
                            Price = 683.67999999999995,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Категория 1",
                            Description = "Изменений роль для роль повышение целесообразности системы проблем значение задач.",
                            Image = "https://picsum.photos/640/480/?image=1048",
                            Name = "Интеллектуальный Кожанный Свитер",
                            Price = 115.73,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Категория 5",
                            Description = "Идейные определения нашей.",
                            Image = "https://picsum.photos/640/480/?image=635",
                            Name = "Маленький Натуральный Куртка",
                            Price = 541.5,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Категория 3",
                            Description = "Повседневная за не существующий принципов а.",
                            Image = "https://picsum.photos/640/480/?image=62",
                            Name = "Потрясающий Кожанный Ботинок",
                            Price = 177.55000000000001,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Категория 2",
                            Description = "Обеспечение подготовке обеспечение систему социально-ориентированный структура базы равным.",
                            Image = "https://picsum.photos/640/480/?image=736",
                            Name = "Лоснящийся Натуральный Кошелек",
                            Price = 906.32000000000005,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Категория 1",
                            Description = "Поэтапного что же поставленных эксперимент богатый с курс.",
                            Image = "https://picsum.photos/640/480/?image=399",
                            Name = "Грубый Резиновый Кошелек",
                            Price = 468.07999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Категория 3",
                            Description = "Социально-ориентированный уровня высшего работы изменений сознания позиции сознания.",
                            Image = "https://picsum.photos/640/480/?image=681",
                            Name = "Интеллектуальный Кожанный Клатч",
                            Price = 486.50999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Категория 5",
                            Description = "Кругу кругу структуры анализа а условий социально-экономическое потребностям рост.",
                            Image = "https://picsum.photos/640/480/?image=999",
                            Name = "Свободный Пластиковый Куртка",
                            Price = 243.81,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Категория 3",
                            Description = "Широким профессионального однако последовательного национальный влечёт систему важную.",
                            Image = "https://picsum.photos/640/480/?image=779",
                            Name = "Большой Неодимовый Носки",
                            Price = 645.00999999999999,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Категория 5",
                            Description = "За активности гражданского.",
                            Image = "https://picsum.photos/640/480/?image=1064",
                            Name = "Практичный Кожанный Ботинок",
                            Price = 108.52,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Категория 1",
                            Description = "Потребностям другой нашей активизации задания играет гражданского сфера от однако.",
                            Image = "https://picsum.photos/640/480/?image=487",
                            Name = "Лоснящийся Кожанный Носки",
                            Price = 814.99000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Категория 2",
                            Description = "Повышению уровня качественно.",
                            Image = "https://picsum.photos/640/480/?image=801",
                            Name = "Невероятный Натуральный Портмоне",
                            Price = 191.84999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Категория 4",
                            Description = "Условий формировании систему позиции сложившаяся профессионального концепция от форм предпосылки.",
                            Image = "https://picsum.photos/640/480/?image=171",
                            Name = "Великолепный Стальной Стол",
                            Price = 93.849999999999994,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Категория 2",
                            Description = "Поэтапного поэтапного начало позиции модернизации создание зависит однако участия материально-технической.",
                            Image = "https://picsum.photos/640/480/?image=534",
                            Name = "Грубый Меховой Майка",
                            Price = 864.98000000000002,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Категория 3",
                            Description = "Влечёт демократической внедрения соображения соответствующих задания забывать прежде инновационный.",
                            Image = "https://picsum.photos/640/480/?image=631",
                            Name = "Интеллектуальный Неодимовый Шарф",
                            Price = 540.52999999999997,
                            SpecialTag = "Топ за свои деньги"
                        });
                });

            modelBuilder.Entity("StoreApi.Model.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("StoreApi.Model.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreApi.Model.CartItem", b =>
                {
                    b.HasOne("StoreApi.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreApi.Model.ShoppingCart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreApi.Model.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
