// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoreApi.Data;

#nullable disable

namespace StoreApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203112018_Add-Null-To-Product")]
    partial class AddNullToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StoreApi.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Категория 1",
                            Description = "Не принимаемых позиции практика степени модели формирования.",
                            Image = "https://picsum.photos/640/480/?image=287",
                            Name = "Интеллектуальный Неодимовый Компьютер",
                            Price = 221.38999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Категория 1",
                            Description = "Однако вызывает сомнений кадров направлений требует социально-ориентированный активом.",
                            Image = "https://picsum.photos/640/480/?image=530",
                            Name = "Великолепный Бетонный Сабо",
                            Price = 607.50999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Категория 4",
                            Description = "Позиции последовательного шагов следует реализация специалистов консультация создаёт.",
                            Image = "https://picsum.photos/640/480/?image=486",
                            Name = "Большой Деревянный Ножницы",
                            Price = 672.72000000000003,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Категория 5",
                            Description = "Целесообразности с соответствующей разнообразный.",
                            Image = "https://picsum.photos/640/480/?image=143",
                            Name = "Потрясающий Кожанный Сабо",
                            Price = 135.63999999999999,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Категория 1",
                            Description = "Демократической новая последовательного проект принимаемых очевидна опыт.",
                            Image = "https://picsum.photos/640/480/?image=711",
                            Name = "Практичный Натуральный Стол",
                            Price = 18.600000000000001,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Категория 4",
                            Description = "Нами собой активизации соображения забывать внедрения активизации участия административных.",
                            Image = "https://picsum.photos/640/480/?image=451",
                            Name = "Практичный Хлопковый Ремень",
                            Price = 349.67000000000002,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Категория 1",
                            Description = "Активности модернизации широкому.",
                            Image = "https://picsum.photos/640/480/?image=626",
                            Name = "Великолепный Кожанный Стул",
                            Price = 43.229999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Категория 2",
                            Description = "Зависит особенности массового вызывает качественно рамки сущности зависит роль воздействия.",
                            Image = "https://picsum.photos/640/480/?image=725",
                            Name = "Невероятный Стальной Ремень",
                            Price = 763.89999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Категория 5",
                            Description = "Мира важную забывать разнообразный широкому.",
                            Image = "https://picsum.photos/640/480/?image=41",
                            Name = "Свободный Неодимовый Куртка",
                            Price = 802.21000000000004,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Категория 5",
                            Description = "Формировании кругу шагов гражданского образом позволяет богатый.",
                            Image = "https://picsum.photos/640/480/?image=481",
                            Name = "Лоснящийся Неодимовый Портмоне",
                            Price = 878.80999999999995,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Категория 1",
                            Description = "Задания массового процесс.",
                            Image = "https://picsum.photos/640/480/?image=427",
                            Name = "Практичный Неодимовый Кошелек",
                            Price = 88.859999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Категория 3",
                            Description = "Проблем интересный поэтапного задача.",
                            Image = "https://picsum.photos/640/480/?image=295",
                            Name = "Великолепный Кожанный Кошелек",
                            Price = 646.84000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Категория 1",
                            Description = "Шагов консультация позиции что общественной.",
                            Image = "https://picsum.photos/640/480/?image=352",
                            Name = "Свободный Меховой Куртка",
                            Price = 451.82999999999998,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Категория 2",
                            Description = "Профессионального прежде насущным новая порядка организации структуры.",
                            Image = "https://picsum.photos/640/480/?image=824",
                            Name = "Грубый Меховой Носки",
                            Price = 189.03999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Категория 2",
                            Description = "Порядка принимаемых равным эксперимент уровня разнообразный.",
                            Image = "https://picsum.photos/640/480/?image=1035",
                            Name = "Практичный Неодимовый Стол",
                            Price = 87.560000000000002,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Категория 4",
                            Description = "Соответствующей модели таким и соответствующей различных создаёт современного.",
                            Image = "https://picsum.photos/640/480/?image=435",
                            Name = "Великолепный Натуральный Портмоне",
                            Price = 48.259999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Категория 5",
                            Description = "Уровня соответствующих базы предпосылки анализа задания вызывает участниками высокотехнологичная.",
                            Image = "https://picsum.photos/640/480/?image=741",
                            Name = "Практичный Меховой Стул",
                            Price = 531.55999999999995,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Категория 1",
                            Description = "Поэтапного задач проблем организации предложений.",
                            Image = "https://picsum.photos/640/480/?image=965",
                            Name = "Интеллектуальный Бетонный Сабо",
                            Price = 758.16999999999996,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Категория 5",
                            Description = "Принципов стороны с формировании.",
                            Image = "https://picsum.photos/640/480/?image=342",
                            Name = "Интеллектуальный Бетонный Ремень",
                            Price = 626.38999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Категория 1",
                            Description = "Социально-ориентированный формированию формировании.",
                            Image = "https://picsum.photos/640/480/?image=1038",
                            Name = "Лоснящийся Неодимовый Ремень",
                            Price = 551.66999999999996,
                            SpecialTag = "Новинка"
                        });
                });

            modelBuilder.Entity("StoreApi.Model.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
