// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoreApi.Data;

#nullable disable

namespace StoreApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StoreApi.Model.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("StoreApi.Model.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderDetailId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("StoreApi.Model.OrderHeader", b =>
                {
                    b.Property<int>("OrderHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderHeaderId"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OrderTotalAmount")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("OrderHeaderId");

                    b.HasIndex("AppUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("StoreApi.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Категория 2",
                            Description = "Управление качественно активом важную.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Свободный Стальной Майка",
                            Price = 738.25,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Категория 4",
                            Description = "Другой от значительной забывать поэтапного повышение уточнения значимость влечёт.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Маленький Натуральный Сабо",
                            Price = 344.80000000000001,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Категория 4",
                            Description = "Опыт соответствующей также.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Большой Натуральный Плащ",
                            Price = 831.44000000000005,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Категория 3",
                            Description = "Сознания потребностям кругу.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Лоснящийся Стальной Компьютер",
                            Price = 157.03,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Категория 2",
                            Description = "Рост проект предпосылки сущности богатый гражданского постоянное играет порядка повышение.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Невероятный Деревянный Стол",
                            Price = 427.49000000000001,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Категория 3",
                            Description = "Значение за обучения интересный принципов форм способствует.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Великолепный Деревянный Ремень",
                            Price = 655.88999999999999,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Категория 2",
                            Description = "Обществом повышение уровня.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Фантастический Хлопковый Портмоне",
                            Price = 352.54000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Категория 1",
                            Description = "В что соответствующей новая зависит же нашей системы обучения поставленных.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Потрясающий Натуральный Стул",
                            Price = 941.02999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Категория 2",
                            Description = "Кадров качественно таким проверки кадровой.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Великолепный Резиновый Сабо",
                            Price = 374.27999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Категория 5",
                            Description = "Богатый формирования повышению.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Интеллектуальный Стальной Кулон",
                            Price = 927.15999999999997,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Категория 5",
                            Description = "Богатый способствует поставленных модели значение широкому.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Интеллектуальный Стальной Клатч",
                            Price = 631.75,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Категория 5",
                            Description = "Потребностям стороны место занимаемых сознания.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Невероятный Резиновый Ножницы",
                            Price = 542.11000000000001,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Категория 4",
                            Description = "Выбранный участниками инновационный форм опыт сфера особенности повседневной активом.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Большой Неодимовый Стол",
                            Price = 787.72000000000003,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Категория 5",
                            Description = "Целесообразности шагов забывать.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Великолепный Кожанный Ремень",
                            Price = 623.96000000000004,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Категория 2",
                            Description = "Дальнейшее таким повышение.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Невероятный Бетонный Ножницы",
                            Price = 824.05999999999995,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Категория 4",
                            Description = "Дальнейшее принципов нашей идейные соответствующей значительной систему общества напрямую.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Большой Хлопковый Сабо",
                            Price = 498.82999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Категория 2",
                            Description = "Обществом роль технологий стороны системы различных изменений разработке изменений интересный.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Эргономичный Гранитный Берет",
                            Price = 221.15000000000001,
                            SpecialTag = "Топ за свои деньги"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Категория 4",
                            Description = "Широким интересный постоянное место подготовке таким.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Потрясающий Кожанный Ремень",
                            Price = 991.74000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Категория 3",
                            Description = "Общественной всего прогрессивного постоянное.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Эргономичный Кожанный Носки",
                            Price = 951.70000000000005,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Категория 2",
                            Description = "Постоянный подготовке консультация отношении рост значительной.",
                            Image = "https://s3.twcstorage.ru/a8f5cea5-14e9-4644-975c-4e58aeeb2499/img7.png",
                            Name = "Потрясающий Хлопковый Куртка",
                            Price = 1.6899999999999999,
                            SpecialTag = "Новинка"
                        });
                });

            modelBuilder.Entity("StoreApi.Model.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("StoreApi.Model.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreApi.Model.CartItem", b =>
                {
                    b.HasOne("StoreApi.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreApi.Model.ShoppingCart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreApi.Model.OrderDetails", b =>
                {
                    b.HasOne("StoreApi.Model.OrderHeader", null)
                        .WithMany("OrderDetailsItems")
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreApi.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreApi.Model.OrderHeader", b =>
                {
                    b.HasOne("StoreApi.Model.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoreApi.Model.OrderHeader", b =>
                {
                    b.Navigation("OrderDetailsItems");
                });

            modelBuilder.Entity("StoreApi.Model.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
